{
 "title": "Unraid NUT UPS Dashboard TR",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "kwhprice", "label": "kWh Price", "query": "4.20" },
   { "name": "currency", "label": "Currency", "query": "₴,$,€,£,C$,kr,¥" },
   { "name": "upsdatasource", "label": "UPS Datasource", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "Input/Output, Energy, Load V, Wh, W",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "input_voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT mean(\"value\") FROM \"modbus_value\" WHERE (\"type_instance\" = 'ups_InputVoltage') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "deye/ac/l1/voltage" }
     ]
    },
    {
     "alias": "day kWh",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "deye/ac/daily_energy_bought" }
     ]
    },
    {
     "alias": "deye Watt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "deye/total power" }
     ]
    },
    {
     "alias": "grid Watt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "deye/ac/total_grid_power" }
     ]
    }
   ]
  },
  {
   "title": "UPS Battery Charge",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 5, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Percent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "deye/battery/soc" }
     ]
    },
    {
     "alias": "Voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "deye/battery/voltage" }
     ]
    },
    {
     "alias": "Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "deye/battery/temperature" }
     ]
    },
    {
     "alias": "Current",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "deye/battery/current" }
     ]
    }
   ]
  },
  {
   "title": "Current UPS Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Watts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "deye/total power" }
     ]
    }
   ]
  },
  {
   "title": "Average UPS Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Watts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "deye/total power" }
     ]
    }
   ]
  },
  {
   "title": "Today's Usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "deye/ac/daily_energy_bought" }
     ]
    }
   ]
  },
  {
   "title": "Today's Cost",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "currencyUAH" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "Costs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT difference(mean(\"value\")) /1000*$kwhprice FROM \"modbus_value\" WHERE (\"type_instance\" = 'ups_Output.Energy') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*$kwhprice" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "deye/ac/daily_energy_bought" }
     ]
    }
   ]
  },
  {
   "title": "Battery charge\\discharge",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "bat day charge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "deye/battery/daily_charge" }
     ]
    },
    {
     "alias": "bat day discharge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "deye/battery/daily_discharge" }
     ]
    }
   ]
  },
  {
   "title": "This Week's Usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "deye/ac/total_energy_bought" }
     ]
    }
   ]
  },
  {
   "title": "This Week's Cost",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "modbus_value",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "/1000*$kwhprice" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "ups_Output.Energy" }
     ]
    }
   ]
  },
  {
   "title": "Time on BAT/LINE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upsd",
     "query": "SELECT INTEGRAL(on_battery) AS \"BATTERY\" FROM (SELECT FLOOR(1/(\"value\"+1)) AS on_battery FROM \"mqtt_consumer\"  WHERE (\"topic\"::tag = 'deye/ac/l1/voltage') AND $timeFilter)\n\n",
     "select": [
      [
       { "params": [ "input_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "query": "SELECT INTEGRAL(on_line) AS \"ONLINE\" FROM (SELECT 1-(FLOOR(1/(value+1))) AS on_line FROM \"mqtt_consumer\"  WHERE (\"topic\"::tag = 'deye/ac/l1/voltage') AND $timeFilter)"
    }
   ]
  },
  {
   "title": "Battery Data",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "bat_percent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "deye/battery/soc" }
     ]
    },
    {
     "alias": "bat_temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "deye/battery/temperature" }
     ]
    },
    {
     "alias": "bat_volt_pos",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "deye/battery/voltage" }
     ]
    },
    {
     "alias": "bat_load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "deye/battery/power" }
     ]
    },
    {
     "alias": "bat_amp_pos",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "deye/battery/current" }
     ]
    },
    {
     "alias": "bat_daily_charge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "deye/battery/daily_charge" }
     ]
    },
    {
     "alias": "bat_daily_discharge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "deye/battery/daily_discharge" }
     ]
    }
   ]
  },
  {
   "title": "UPS Load, W",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "GRID Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "deye/ac/total_grid_power" }
     ]
    },
    {
     "alias": "DEYE Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "deye/total power" }
     ]
    },
    {
     "alias": "L1 Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "deye/ac/l1/power" }
     ]
    }
   ]
  }
 ]
}